unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-space
set -g mouse on
set -g mode-keys vi
set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind -n M-l next-window
bind -n M-h previous-window
bind-key -n M-z resize-pane -Z
bind-key w kill-pane
bind-key q kill-window
bind-key s split-window -v
bind-key v split-window -h
bind-key t choose-session
bind-key -n M-H resize-pane -L 5
bind-key -n M-J resize-pane -D 5
bind-key -n M-K resize-pane -U 5
bind-key -n M-L resize-pane -R 5
bind Tab last-window
bind e new-session
bind E kill-session

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# Catppuccin (commented out)
# set -g @plugin 'catppuccin/tmux#v2.1.2'
# set -g @catppuccin_window_status_style "rounded"
# set -g status-left '#("#{pane_current_path}")'
# set -g status-right "#{E:@catppuccin_status_application}"

# Minimal tmux - Black Metal theme
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-bg '#486e6f'
set -g @minimal-tmux-fg '#c1c1c1'
set -g pane-border-style 'fg=#3f3f3f'
set -g pane-active-border-style 'fg=#486e6f'
set -g @minimal-tmux-justify 'left'
set -g @minimal-tmux-use-arrow false
set-option -g status-position bottom
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ',xterm-256color:Tc'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
